insert into bien (adresse, superficie, etat, type, ville) values ('84 Buena Vista Plaza', 535, 'dispo', 'appartement', 'Tébessa');
insert into bien (adresse, superficie, etat, type, ville) values ('1 Briar Crest Pass', 501, 'dispo', 'appartement', 'Naâma');
insert into bien (adresse, superficie, etat, type, ville) values ('6970 Fordem Alley', 316, 'dispo', 'villa', 'Relizane');
insert into bien (adresse, superficie, etat, type, ville) values ('3865 Homewood Point', 411, 'dispo', 'appartement', 'Sétif');
insert into bien (adresse, superficie, etat, type, ville) values ('38244 School Crossing', 574, 'dispo', 'appartement', 'Algiers');
insert into bien (adresse, superficie, etat, type, ville) values ('7 Waxwing Center', 586, 'dispo', 'appartement', 'Bordj Bou Arréridj');
insert into bien (adresse, superficie, etat, type, ville) values ('021 Buhler Road', 466, 'dispo', 'appartement', 'Tamanrasset');
insert into bien (adresse, superficie, etat, type, ville) values ('5 Michigan Crossing', 416, 'dispo', 'appartement', 'Ouargla');
insert into bien (adresse, superficie, etat, type, ville) values ('6486 Scott Parkway', 452, 'dispo', 'villa', 'Chlef');
insert into bien (adresse, superficie, etat, type, ville) values ('91 Corry Center', 433, 'dispo', 'appartement', 'Souk Ahras');
insert into bien (adresse, superficie, etat, type, ville) values ('44 Superior Road', 556, 'dispo', 'villa', 'Constantine');
insert into bien (adresse, superficie, etat, type, ville) values ('1 Katie Park', 593, 'dispo', 'appartement', 'Aïn Témouchent');
insert into bien (adresse, superficie, etat, type, ville) values ('23254 Stoughton Terrace', 284, 'dispo', 'maison', 'Bordj Bou Arréridj');
insert into bien (adresse, superficie, etat, type, ville) values ('09 Arkansas Trail', 589, 'dispo', 'villa', 'Tlemcen');
insert into bien (adresse, superficie, etat, type, ville) values ('4 Bowman Street', 312, 'dispo', 'appartement', 'Khenchela');
insert into bien (adresse, superficie, etat, type, ville) values ('75787 Heath Drive', 350, 'dispo', 'appartement', 'In Salah');
insert into bien (adresse, superficie, etat, type, ville) values ('08 Jenifer Court', 527, 'dispo', 'villa', 'Illizi');
insert into bien (adresse, superficie, etat, type, ville) values ('03692 Mccormick Center', 510, 'dispo', 'maison', 'Tlemcen');
insert into bien (adresse, superficie, etat, type, ville) values ('58557 Merrick Avenue', 403, 'dispo', 'villa', 'Béjaïa');
insert into bien (adresse, superficie, etat, type, ville) values ('2 Onsgard Alley', 338, 'dispo', 'appartement', 'Tiaret');
insert into bien (adresse, superficie, etat, type, ville) values ('4300 Hanson Lane', 534, 'dispo', 'maison', 'Sidi Bel Abbès');
insert into bien (adresse, superficie, etat, type, ville) values ('54 Magdeline Plaza', 443, 'dispo', 'maison', 'Jijel');
insert into bien (adresse, superficie, etat, type, ville) values ('7 Glendale Court', 305, 'dispo', 'villa', 'Algiers');
insert into bien (adresse, superficie, etat, type, ville) values ('58 7th Center', 395, 'dispo', 'villa', 'M’Sila');
insert into bien (adresse, superficie, etat, type, ville) values ('607 Talmadge Pass', 473, 'dispo', 'villa', 'Tipaza');
insert into bien (adresse, superficie, etat, type, ville) values ('231 Fair Oaks Plaza', 378, 'dispo', 'villa', 'Naâma');
insert into bien (adresse, superficie, etat, type, ville) values ('4 Bultman Center', 291, 'dispo', 'maison', 'Oran');
insert into bien (adresse, superficie, etat, type, ville) values ('5003 Park Meadow Park', 344, 'dispo', 'maison', 'Boumerdès');
insert into bien (adresse, superficie, etat, type, ville) values ('7 Marcy Hill', 464, 'dispo', 'villa', 'El Oued');
insert into bien (adresse, superficie, etat, type, ville) values ('86229 Aberg Terrace', 268, 'dispo', 'villa', 'Algiers');
insert into bien (adresse, superficie, etat, type, ville) values ('0 Sheridan Point', 371, 'dispo', 'maison', 'Béni Abbès');
insert into bien (adresse, superficie, etat, type, ville) values ('3429 Brown Parkway', 402, 'dispo', 'maison', 'Bordj Badji Mokhtar');
insert into bien (adresse, superficie, etat, type, ville) values ('0 Eastwood Avenue', 308, 'dispo', 'appartement', 'Bordj Bou Arréridj');
insert into bien (adresse, superficie, etat, type, ville) values ('880 Esch Terrace', 266, 'dispo', 'appartement', 'Chlef');
insert into bien (adresse, superficie, etat, type, ville) values ('1624 Almo Plaza', 538, 'dispo', 'appartement', 'Tissemsilt');
insert into bien (adresse, superficie, etat, type, ville) values ('5 Old Shore Court', 436, 'dispo', 'appartement', 'M’Sila');
insert into bien (adresse, superficie, etat, type, ville) values ('5512 Lerdahl Alley', 474, 'dispo', 'appartement', 'Mascara');
insert into bien (adresse, superficie, etat, type, ville) values ('3264 Ridgeview Hill', 574, 'dispo', 'appartement', 'Tamanrasset');
insert into bien (adresse, superficie, etat, type, ville) values ('82472 Swallow Avenue', 385, 'dispo', 'villa', 'Khenchela');
insert into bien (adresse, superficie, etat, type, ville) values ('90 Jana Court', 266, 'dispo', 'appartement', 'El Meniaa');
insert into bien (adresse, superficie, etat, type, ville) values ('8 Wayridge Avenue', 584, 'dispo', 'appartement', 'Biskra');
insert into bien (adresse, superficie, etat, type, ville) values ('247 Evergreen Court', 600, 'dispo', 'appartement', 'Blida');
insert into bien (adresse, superficie, etat, type, ville) values ('464 East Avenue', 358, 'dispo', 'appartement', 'Biskra');
insert into bien (adresse, superficie, etat, type, ville) values ('9678 Forster Hill', 592, 'dispo', 'maison', 'Souk Ahras');
insert into bien (adresse, superficie, etat, type, ville) values ('97 Bayside Lane', 422, 'dispo', 'villa', 'Ouled Djellal');
insert into bien (adresse, superficie, etat, type, ville) values ('03 Mandrake Trail', 592, 'dispo', 'appartement', 'M’Sila');
insert into bien (adresse, superficie, etat, type, ville) values ('37 Beilfuss Crossing', 472, 'dispo', 'appartement', 'Bordj Badji Mokhtar');
insert into bien (adresse, superficie, etat, type, ville) values ('50263 Westridge Crossing', 346, 'dispo', 'villa', 'Bordj Bou Arréridj');
insert into bien (adresse, superficie, etat, type, ville) values ('1145 Victoria Lane', 524, 'dispo', 'villa', 'Bouira');
insert into bien (adresse, superficie, etat, type, ville) values ('6 Red Cloud Junction', 380, 'dispo', 'maison', 'Touggourt');
insert into bien (adresse, superficie, etat, type, ville) values ('8 Holy Cross Way', 359, 'dispo', 'villa', 'Béjaïa');
insert into bien (adresse, superficie, etat, type, ville) values ('3129 Miller Lane', 365, 'dispo', 'villa', 'Biskra');
insert into bien (adresse, superficie, etat, type, ville) values ('55 Troy Junction', 512, 'dispo', 'maison', 'Algiers');
insert into bien (adresse, superficie, etat, type, ville) values ('49972 Warbler Lane', 426, 'dispo', 'villa', 'Mila');
insert into bien (adresse, superficie, etat, type, ville) values ('98 Morningstar Road', 556, 'dispo', 'appartement', 'Béchar');
insert into bien (adresse, superficie, etat, type, ville) values ('4 Cottonwood Point', 299, 'dispo', 'maison', 'Aïn Defla');
insert into bien (adresse, superficie, etat, type, ville) values ('19 Springs Road', 250, 'dispo', 'maison', 'Tizi Ouzou');
insert into bien (adresse, superficie, etat, type, ville) values ('14326 Rigney Terrace', 406, 'dispo', 'maison', 'Mascara');
insert into bien (adresse, superficie, etat, type, ville) values ('25 Lakeland Way', 503, 'dispo', 'appartement', 'Djelfa');
insert into bien (adresse, superficie, etat, type, ville) values ('88075 International Terrace', 259, 'dispo', 'appartement', 'Oran');
insert into bien (adresse, superficie, etat, type, ville) values ('6 Marquette Plaza', 391, 'dispo', 'villa', 'El Meghaier');
insert into bien (adresse, superficie, etat, type, ville) values ('261 Prairie Rose Hill', 497, 'dispo', 'maison', 'Batna');
insert into bien (adresse, superficie, etat, type, ville) values ('000 Towne Drive', 535, 'dispo', 'villa', 'In Salah');
insert into bien (adresse, superficie, etat, type, ville) values ('54197 Westport Center', 265, 'dispo', 'villa', 'Boumerdès');
insert into bien (adresse, superficie, etat, type, ville) values ('8781 Arapahoe Park', 406, 'dispo', 'villa', 'Bordj Bou Arréridj');
insert into bien (adresse, superficie, etat, type, ville) values ('21831 Old Shore Street', 259, 'dispo', 'villa', 'Algiers');
insert into bien (adresse, superficie, etat, type, ville) values ('792 Russell Junction', 286, 'dispo', 'maison', 'Illizi');
insert into bien (adresse, superficie, etat, type, ville) values ('3011 Welch Park', 559, 'dispo', 'villa', 'Bordj Bou Arréridj');
insert into bien (adresse, superficie, etat, type, ville) values ('9698 Ridgeview Center', 390, 'dispo', 'villa', 'Mascara');
insert into bien (adresse, superficie, etat, type, ville) values ('20153 Paget Parkway', 561, 'dispo', 'maison', 'Souk Ahras');
insert into bien (adresse, superficie, etat, type, ville) values ('5 La Follette Hill', 380, 'dispo', 'maison', 'Mostaganem');
insert into bien (adresse, superficie, etat, type, ville) values ('81155 Colorado Crossing', 413, 'dispo', 'appartement', 'Biskra');
insert into bien (adresse, superficie, etat, type, ville) values ('4346 Red Cloud Circle', 303, 'dispo', 'maison', 'Béjaïa');
insert into bien (adresse, superficie, etat, type, ville) values ('35039 Calypso Hill', 584, 'dispo', 'appartement', 'Béjaïa');
insert into bien (adresse, superficie, etat, type, ville) values ('92 Monterey Park', 489, 'dispo', 'maison', 'Batna');
insert into bien (adresse, superficie, etat, type, ville) values ('084 John Wall Street', 403, 'dispo', 'maison', 'El Meniaa');
insert into bien (adresse, superficie, etat, type, ville) values ('423 Buhler Way', 431, 'dispo', 'maison', 'Tébessa');
insert into bien (adresse, superficie, etat, type, ville) values ('89244 Anderson Way', 487, 'dispo', 'appartement', 'Djelfa');
insert into bien (adresse, superficie, etat, type, ville) values ('36481 Monica Center', 549, 'dispo', 'maison', 'Souk Ahras');
insert into bien (adresse, superficie, etat, type, ville) values ('88874 Claremont Road', 268, 'dispo', 'villa', 'Batna');
insert into bien (adresse, superficie, etat, type, ville) values ('7758 Bartillon Center', 470, 'dispo', 'appartement', 'Algiers');
insert into bien (adresse, superficie, etat, type, ville) values ('660 Summit Parkway', 284, 'dispo', 'villa', 'Skikda');
insert into bien (adresse, superficie, etat, type, ville) values ('9 Spohn Hill', 536, 'dispo', 'maison', 'Touggourt');
insert into bien (adresse, superficie, etat, type, ville) values ('51 Tennessee Drive', 482, 'dispo', 'villa', 'Annaba');
insert into bien (adresse, superficie, etat, type, ville) values ('4 Troy Hill', 339, 'dispo', 'maison', 'Relizane');
insert into bien (adresse, superficie, etat, type, ville) values ('16 Springview Crossing', 258, 'dispo', 'villa', 'Tipaza');
insert into bien (adresse, superficie, etat, type, ville) values ('6 Ridge Oak Place', 365, 'dispo', 'maison', 'Djelfa');
insert into bien (adresse, superficie, etat, type, ville) values ('0383 Algoma Avenue', 459, 'dispo', 'maison', 'Sidi Bel Abbès');
insert into bien (adresse, superficie, etat, type, ville) values ('627 Glendale Trail', 351, 'dispo', 'maison', 'Tindouf');
insert into bien (adresse, superficie, etat, type, ville) values ('53 Melrose Junction', 447, 'dispo', 'villa', 'Tamanrasset');
insert into bien (adresse, superficie, etat, type, ville) values ('1169 Elmside Park', 474, 'dispo', 'maison', 'Guelma');
insert into bien (adresse, superficie, etat, type, ville) values ('77 Transport Point', 359, 'dispo', 'villa', 'Tissemsilt');
insert into bien (adresse, superficie, etat, type, ville) values ('95069 Superior Plaza', 516, 'dispo', 'appartement', 'Tissemsilt');
insert into bien (adresse, superficie, etat, type, ville) values ('72879 Linden Point', 491, 'dispo', 'maison', 'Laghouat');
insert into bien (adresse, superficie, etat, type, ville) values ('8 Summer Ridge Park', 502, 'dispo', 'villa', 'Boumerdès');
insert into bien (adresse, superficie, etat, type, ville) values ('0 Loeprich Way', 435, 'dispo', 'villa', 'In Guezzam');
insert into bien (adresse, superficie, etat, type, ville) values ('497 Declaration Point', 561, 'dispo', 'appartement', 'Relizane');
insert into bien (adresse, superficie, etat, type, ville) values ('1 Elmside Circle', 574, 'dispo', 'villa', 'Adrar');
insert into bien (adresse, superficie, etat, type, ville) values ('5702 Ramsey Drive', 258, 'dispo', 'maison', 'Boumerdès');
insert into bien (adresse, superficie, etat, type, ville) values ('0942 Lerdahl Avenue', 594, 'dispo', 'villa', 'Skikda');
